### PR TITLE
[Feature] Implementing Links For Expenses And Tasks | Invoices

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the implementation of linking "linked" expenses and tasks to an invoice on the invoice slider. Screenshot:

Screenshot 2024-07-23 at 19 47 22

`Note`: We are missing the "linked_expense" and "linked_task" translation keywords that I used throughout the implementation. If you would agree, please just add them there.

Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah we can change the translations to just Expense / Task, no need for the new translation on these.

**Comment by Civolilah** [comment]
> @Civolilah we can change the translations to just Expense / Task, no need for the new translation on these.

@turbo124 Sure, the translations have been changed. Screenshot:

Screenshot 2024-07-24 at 11 23 47

Let me know your thoughts.

**Review by beganovich — APPROVED** [review]

**Comment by beganovich** [comment]
Looks good, cc @Civolilah for conflicts.

**Comment by beganovich** [comment]
cc @Civolilah we got another one.

**Comment by Civolilah** [comment]
> cc @Civolilah we got another one.

@beganovich Fixed!

**Pull request merged**
