### PR TITLE
[Cleanup] Refactoring Tabs | Invoices && Tests Adjustment

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes refactoring the invoice creation and edit pages with the implementation of new tabs, along with refactoring the current ones. Screenshots:

Screenshot 2024-07-18 at 02 11 45

Screenshot 2024-07-18 at 02 13 41

Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
chunk-VPTIPXRI.js?v=9b9244eb:19409 Uncaught TypeError: emailRecords?.map is not a function (when clicking on the Email History)

Also, need a clean way to navigate back from viewing the invoice history

**Comment by turbo124** [comment]
looks good!

**Comment by beganovich** [comment]
Looks good, but I'd suggest a tiny UI change.

I think cards look kinda weird stretching all the way, so I suggest w-2/3.

Before and after:

image
image

Let me know what you think.

**Comment by Civolilah** [comment]
> Looks good, but I'd suggest a tiny UI change.
> 
> I think cards look kinda weird stretching all the way, so I suggest w-2/3.
> 
> Before and after:
> 
> image image
> 
> Let me know what you think.

@beganovich Yes, I definitely agree with you. The only change I made from out of your suggestions is making the cards full width on all screens except xl. So, cards will have full width until the user reaches xl screens, I think this fits best. I have made these changes. Let me know your thoughts.

**Comment by beganovich** [comment]
Looks good, can you please fix merge conflicts?

**Pull request merged**
