### PR TITLE
[Cleanup] Api WebHook Pages - Refactoring

### PR DESCRIPTION
**Pull request by Civolilah**
Here are screenshots of the implemented refactoring for WebHook pages:

Screenshot 2023-01-25 at 14 44 13

Screenshot 2023-01-25 at 14 44 25

Screenshot 2023-01-25 at 14 44 49

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah 

can we please move the headers to the right so they are aligned under the other form elements please.

**Comment by Civolilah** [comment]
> 



> @Civolilah
> 
> can we please move the headers to the right so they are aligned under the other form elements please.

@turbo124 Sure, I refactored UI for headers field and it looks like this:

Screenshot 2023-01-26 at 01 30 37

@beganovich I leave the whole logic as it was.

**Comment by turbo124** [comment]
@Civolilah looks good, please increase the width of the header inputs to fill please.

**Comment by Civolilah** [comment]
> @Civolilah looks good, please increase the width of the header inputs to fill please.

@beganovich Sure, it has been changed, now the inputs will fit the content with a small space between them just to separate them. It looks like this:

Screenshot 2023-01-26 at 15 04 43

**Comment by turbo124** [comment]
Please change header translation string to

`add_header`

**Comment by Civolilah** [comment]
> 
@turbo124 Changed!

**Comment by turbo124** [comment]
:+1:

**Pull request merged**
