### PR TITLE
[Cleanup] Implementing "View Portal" Action On Contacts Card | Client Overview Page

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the implementation of the "View Portal" action on the contact's card on the client overview page. Screenshot:

Screenshot 2024-09-16 at 20 31 07

Let me know your thoughts.

### CODE REVIEW

**Comment by Civolilah** [comment]
@turbo124 The approach here has changed, so every contact will have two icons: one for opening a new tab with the client portal and another for copying the client portal URL. Screenshot:

Screenshot 2024-09-17 at 00 54 10

Let me know your thoughts.

**Comment by turbo124** [comment]
@Civolilah we'll want to include the text 

'client_portal' translation and have the hyperlink on that navigate the user to the client portal, adjacent to that will be the copy clipboard.

it isn't clear from this current iteration what these two buttons actually do.

**Comment by Civolilah** [comment]
> @Civolilah we'll want to include the text
> 
> 'client_portal' translation and have the hyperlink on that navigate the user to the client portal, adjacent to that will be the copy clipboard.
> 
> it isn't clear from this current iteration what these two buttons actually do.

@turbo124 If I understood you correctly, you want to have the tooltip text for the client portal navigation icon also. Here is the tooltip added, so all of those three icons have the tooltip text:

Screenshot 2024-09-17 at 14 29 12

Let me know your thoughts.

**Comment by Civolilah** [comment]
@turbo124 As we discussed on Slack, the approach here has changed and it is being implemented right now. Screenshot:

Screenshot 2024-09-19 at 21 10 23

Let me know your thoughts.

**Comment by turbo124** [comment]
@Civolilah this menu actions can now be removed:

image

**Comment by turbo124** [comment]
@Civolilah the URL format is broken now? it looks like a relative url is being used?

**Review by beganovich — APPROVED** [review]

**Pull request merged**
