### PR TITLE
Fixes for "run template"

### PR DESCRIPTION
**Pull request by beganovich**
This fixes few bugs with run template actions and implements the run template for bulk actions.

### CODE REVIEW

**Comment by turbo124** [comment]
@beganovich looks good, just need to sort out the download pdf action, i think it is a content / mime type issue not being passed in the headers?

**Comment by beganovich** [comment]
@turbo124 Fixed :+1:

**Comment by turbo124** [comment]
Looks good, thanks!

**Review by turbo124 — APPROVED** [review]

**Comment by turbo124** [comment]
@beganovich looks good, just needs conflicts resolved and then good for merge.

**Pull request merged**
