### PR TITLE
[Bugfix] Exclusion Of Owner User From Users List

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the implementation of excluding the account owner from the list of users when the sub-user is logged in. Additionally, a test for this case has been implemented. Let me know your thoughts.

### CODE REVIEW

**Comment by beganovich** [comment]
@turbo124 any chance of getting this as an API feature? Like a filter.

**Comment by turbo124** [comment]
sure, i've added in

?hideOwnerUsers=true which can be added to the query parameters on user route

**Comment by beganovich** [comment]
Abedin can you revert these changes from the PR and make sure we use filter, this should simplify code a lot. Thanks!

**Comment by Civolilah** [comment]
> Abedin can you revert these changes from the PR and make sure we use filter, this should simplify code a lot. Thanks!

@beganovich Sure thing, the approach has been changed, and I'm leaving the test as it is since the output should remain the same. @turbo124, I guess we need to await the updating of the API for merging this?

**Comment by turbo124** [comment]
@beganovich ready for merge please.

**Review by beganovich — APPROVED** [review]

**Pull request merged**
