### PR TITLE
[Cleanup] Formatting Date Properties For Invoices With Timezone

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes formatting of `next_send_date` and `last_sent_date` properties for invoices in all tables and in the invoice slider. Let me know your thoughts.

### CODE REVIEW

**Comment by Civolilah** [comment]
@turbo124 Once I checked the format of the `next_send_date` column, I noticed there was also a `last_sent_date` column, so I considered it as an additional formatting requirement. Am I right?

**Comment by turbo124** [comment]
nice thinking, unfortunately the dates last_sent_date and the reminder1's are only date's not datetime's it would have been nice to also calculate this, but unfortunately not possible, as such, lets just target the single next_send_date

**Comment by Civolilah** [comment]
> Please check comments on #2232 and make sure it aligns here, too 👍

@beganovich Sure, it has been aligned.

**Comment by beganovich** [comment]
Ping for merge conflicts :+1:

**Pull request merged**
