### PR TITLE
[Cleanup] Avoiding Third Party Links On Self-Hosted | RSMS-INTER css

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes adjusting the logic in the website header to avoid the usage of third-party URLs on `SELF-HOSTED`. Previously, we had the third-party URL (`https://rsms.me/inter/inter.css`) set in the header, importing the CSS. However, now for the SELF-HOSTED platform, we will import that CSS from a locally added file. For `HOSTED`, the mentioned third-party URL will still be used instead of a local file. Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
@beganovich does this work with our cf deployment?

**Comment by beganovich** [comment]
It should yep as it's just a static asset. 

However, I wonder why don't we just bundle it always? Why ever load from the 3rd party.. would be much simpler.

**Comment by turbo124** [comment]
@beganovich i think bundling makes sense.

**Comment by Civolilah** [comment]
> @beganovich i think bundling makes sense.

@beganovich @turbo124 Sure, then we will simply have local loading of the needed files, avoiding third-party URLs on the `HOSTED` platform as well. It's done. Let me know your thoughts.

**Review by beganovich — APPROVED** [review]

**Pull request merged**
