### PR TITLE
[Cleanup] Refactoring Of Common Actions Section | Icons Implementation

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes refactoring of the common actions section for invoices. Instead of having buttons, we now have icons with tooltips. Screenshot:

Screenshot 2023-11-25 at 19 22 13

Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah 

looks good, two small improvements:

1. We can remove the cap on the number of actions now that we are using icons.
2. Is it possible to sort the order of appearance? Or do these need to be fixed?

**Comment by Civolilah** [comment]
> @Civolilah
> 
> looks good, two small improvements:
> 
> 1. We can remove the cap on the number of actions now that we are using icons.
> 2. Is it possible to sort the order of appearance? Or do these need to be fixed?

@turbo124 Certainly, I will remove the cap on the number of possible actions. Additionally, having the option for ordering would be great. Would you like to implement it within the modal or use drag-and-drop for the list of selected actions?

**Comment by turbo124** [comment]
In the modal for reordering please

**Comment by Civolilah** [comment]
@turbo124 The functionality for reordering of actions, along with the removal of the cap on the number of actions, has been implemented. Let me know your thoughts.

**Comment by Civolilah** [comment]
> In the modal for reordering please

@turbo124 The functionality for reordering of actions, along with the removal of the cap on the number of actions, has been implemented. Let me know your thoughts.

**Comment by turbo124** [comment]
Looks good!!

**Review by beganovich — APPROVED** [review]

**Pull request merged**
