### PR TITLE
[Feature] Implementing Delete Functionality For Gateway Tokens

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR implements the functionality to delete gateway tokens. Screenshot:

Screenshot 2024-12-11 at 15 13 15

Let me know your thoughts.

### CODE REVIEW

**Comment by Civolilah** [comment]
@turbo124 From my perspective, a delete button fits much better in this context compared to a trash icon.

**Comment by Civolilah** [comment]
@turbo124 The solution has been adjusted as we discussed on Slack. We now have arrows on buttons that will display the delete option, similar to how we handle additional save options for some entities. Let me know your thoughts.

**Comment by turbo124** [comment]
resize_borked

I think we need to rethink where we have this dropdown so that it is always visible

**Comment by Civolilah** [comment]
@turbo124 As we discussed on Slack, the width of cards has been adjusted for the Client show page. Let me know your thoughts.

**Review by beganovich — APPROVED** [review]

**Pull request merged**
