### PR TITLE
[Feature] Bank rules

### PR DESCRIPTION
**Pull request by Civolilah**
Here are screenshots of implemented feature `Bank transaction rules`:

Screenshot 2023-02-07 at 22 25 46

Screenshot 2023-02-07 at 22 26 12

Screenshot 2023-02-07 at 22 26 26

@beganovich @turbo124 The PR is in the draft because of condition to show it only for hosted users. So, after David's approval I will change condition and set it to ready for Ben's review.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah is this pending review by me or @beganovich

**Comment by Civolilah** [comment]
> @Civolilah is this pending review by me or @beganovich

@turbo124 You approved this one and sent me message on the Slack for the same. So we just need @beganovich review here.

**Comment by beganovich** [comment]
Before reviewing this:

1. UI language: I assume you took inspiration from Flutter or Material UI, but this looks completely off compared to the rest of the app. I'd suggest a table-layout, the same as for the invoices (products table) as we are obviously working with table-like UI.

2. How do I even get to this page? I was able to check it by manually appending /transaction_rules in the URL, but I wasn't able to find the button in the UI.

**Comment by Civolilah** [comment]
> Before reviewing this:
> 
> 1. UI language: I assume you took inspiration from Flutter or Material UI, but this looks completely off compared to the rest of the app. I'd suggest a table-layout, the same as for the invoices (products table) as we are obviously working with table-like UI.
> 2. How do I even get to this page? I was able to check it by manually appending /transaction_rules in the URL, but I wasn't able to find the button in the UI.

@beganovich 

1. Sure, the UI has been slightly change to make it consistent with the rest of the project. So, here is the screenshot of new UI for transaction rule form:

Screenshot 2023-02-15 at 15 22 54

2. Actually, this feature is available only for `HOSTED` users so because of testing it locally the button has been hidden. Here is the screenshot how it looks and where is the button when I remove condition for `HOSTED` platform.

Screenshot 2023-02-15 at 15 25 48

**Comment by turbo124** [comment]
@beganovich is branch blocked by permissions? We may want to create a label for anything that is blocked.

**Pull request merged**
