### PR TITLE
E-invoicing: Remove invalid company alert

### PR DESCRIPTION
**Pull request by beganovich**
This removes the following alert:

image

### CODE REVIEW

**Comment by beganovich** [comment]
@turbo124 we still have another reference to invalid client with "Client details are invalid or missing".

Is this one redundant do or it's actually useful?

**Comment by Civolilah** [comment]
> @turbo124 we still have another reference to invalid client with "Client details are invalid or missing".
> 
> Is this one redundant do or it's actually useful?

@beganovich I believe Dave decided to have the banner only on the Invoice edit page's E-Invoice tab. I actually worked on that task and removed it in this PR: #2186 . We considered it unnecessary on the E-Invoice settings page.

**Comment by beganovich** [comment]
@Civolilah should I close this PR then?

**Comment by Civolilah** [comment]
> @Civolilah should I close this PR then?

@beganovich Dave has already QA'd it for you, no worries. You can merge it - I'll merge your changes into my PR.

**Pull request merged**
