### PR TITLE
[Feature] Backup-restore

### PR DESCRIPTION
**Pull request by Civolilah**
Here are screenshots of solution for company backup and restore under settings:

Screenshot 2022-12-15 at 00 13 05

Screenshot 2022-12-15 at 00 13 15

### CODE REVIEW

**Comment by turbo124** [comment]
Backup / Restore is an alias for Company Export / Import.

We'll want to move the company import from the company details section into here.

**Comment by turbo124** [comment]
This is the restore screen only, we'll want to add in the company export screen in another card beneath this.

I am adding in some additional translations for this, instead of zip_file please use `company_backup_file`

and i also have a help text message labelled: company_backup_file_help

**Comment by Civolilah** [comment]
> 

@turbo124 This part is also implemented! I've updated the PR description of what the new UI looks like. In the current implementation with the additional export function, we are missing the keywords `backup` and `export_company`.

**Comment by Civolilah** [comment]
@turbo124 As we discussed on the Slack additional renaming changes have been finished!

**Comment by turbo124** [comment]
@Civolilah thank you. @beganovich LGTM

**Comment by beganovich** [comment]
Looks good, thanks :+1:

**Pull request merged**
