### PR TITLE
[Feature] Report Schedule

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the implementation of the Report Schedule functionality from the Report Schedule page, along with the test implementation for them. Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah 

Looks great!

One small UI change. Scheduled reports will always be emails, so can we just disable  the send_email prop

```
![image](https://github.com/invoiceninja/ui/assets/5827962/d4f59fcd-2afa-4e9d-8424-a999cac7b09c)
```

so that it cannot be changed from always true

**Comment by turbo124** [comment]
@Civolilah 

One small thin, in the list view, can you add the report type:

image

**Comment by Civolilah** [comment]
> @Civolilah
> 
> One small thin, in the list view, can you add the report type:
> 
> image

**Comment by Civolilah** [comment]
> @Civolilah
> 
> One small thin, in the list view, can you add the report type:
> 
> image

@turbo124 Done: 

Screenshot 2023-12-26 at 02 35 37

**Review by beganovich — APPROVED** [review]

**Pull request merged**
