### PR TITLE
User preferences 

### PR DESCRIPTION
**Pull request by beganovich**
This allows us to store preferences per user.

### CODE REVIEW

**Comment by beganovich** [comment]
Ping @turbo124 for the first pass on this. It should allow you to change default dashboard view :)

**Comment by turbo124** [comment]
This looks perfect.

**Comment by turbo124** [comment]
Just checking this again. It seems that after saving. If I log back in, the default chartt configuration is not implemented?

**Comment by turbo124** [comment]
Still not working.

Also, Currency list, should only be those in the drop down

image


We are not storing the day/week/month option

and the preferences are not restored on login.

**Comment by beganovich** [comment]
Ping @turbo124 for another QA pass.

**Comment by turbo124** [comment]
@beganovich 

there are issues with this, dashboard does not work, perhaps due to recent updates for charts that I made?

**Comment by beganovich** [comment]
Ping @turbo124 for another QA pass.

**Comment by turbo124** [comment]
feedback in jira

**Comment by beganovich** [comment]
Ping @turbo124 for another QA pass.

**Comment by turbo124** [comment]
:rocket:

**Pull request merged**
