### PR TITLE
[Feature] Transaction Convert Bulk Action | Implementation

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the implementation of a new transaction bulk action (`Convert`). Additionally, the PR includes a slight refactoring of the code structure related to query files to make it consistent with the rest of the project. Screenshot:

Screenshot 2023-08-09 at 17 36 47

Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
Looks good, thanks!

**Comment by beganovich** [comment]
cc #1008

**Comment by Civolilah** [comment]
@beganovich Resolved conflicts, ready for merge from my end.

**Review by beganovich — APPROVED** [review]
Thanks!

**Pull request merged**
