### PR TITLE
[Feature] Convert currency option - Expense pages

### PR DESCRIPTION
**Pull request by Civolilah**
@turbo124 Currently, PR contains all parts of the functionality except the comparison of two selected currencies. We just need to talk about this part further and include the logarithm to calculate it.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah the logic already exists in the application for the comparison of the currencies, however the rounding needs to be fixed.

**Comment by turbo124** [comment]
When the company option to convert currency is not selected, when i manually toggle the Convert Currency toggle in an expense, the toggle never persists afterwards.

you may need to add a check to see if a converted amount is set on the expense. If yes, then it means the toggle should be on for that record so that the user can see the amount.

**Comment by Civolilah** [comment]
> 

@turbo124 The logic has been improved so that now if we have any `foreign_amount` on a particular expense, the `convert_currency` fields will show if they are turned off in the settings.

**Comment by turbo124** [comment]
@Civolilah 

Sorry, this still is not working for me. It looksl ike we set the foreign currency on save regardless. It appears that we monitor invoice_currency_id if a conversion has been set by the user.

**Comment by Civolilah** [comment]
> 

@turbo124 As we discussed on the Slack this behaviour is also improved and on my end it looks good. Let me know about your thoughts.

**Comment by turbo124** [comment]
LGTM!

**Review by beganovich — APPROVED** [review]
Looks good, thanks 👍

**Pull request merged**
