### PR TITLE
[Bugfix] Invalid Task Time Log Values Handling

### LINKED ISSUE #1968: Another "UNIX epoch time reset" glitch when deleting parts of timecodes in task details' timelogging fields
Similar to issue #1718 and #1361, but still occurs as of today in the Pro v5 SaaS version:

https://github.com/user-attachments/assets/5c39fd42-709d-4239-bb15-989695939375

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes adding logic for returning fallback values on task time logs when invalid values are entered. Let me know your thoughts.

Closes #1968

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah if you enable show end date in Settings (Settings > Task settings > show end date)

Then when adding a new item on a task i get 404.

**Comment by Civolilah** [comment]
> @Civolilah if you enable show end date in Settings (Settings > Task settings > show end date)
> 
> Then when adding a new item on a task i get 404.

@turbo124 As we discussed today on Slack, we adjusted the behavior when creating new time logs on the task table. That issue will be fixed in #1995 , so can we review this one only based on the bug related to the onBlur event and invalid values?

**Comment by turbo124** [comment]
@Civolilah should this be reviewed after we merge the blocking issue into develop?

**Comment by Civolilah** [comment]
> @Civolilah should this be reviewed after we merge the blocking issue into develop?

@turbo124 Yeah, let's wait for merging the issue with adding time_logs and then we will review this one more time to ensure it works perfectly fine. But, in general, the issues are totally separate.

**Comment by Civolilah** [comment]
> > @Civolilah should this be reviewed after we merge the blocking issue into develop?
> 
> @turbo124 Yeah, let's wait for merging the issue with adding time_logs and then we will review this one more time to ensure it works perfectly fine. But, in general, the issues are totally separate.

**Comment by Civolilah** [comment]
@turbo124 Confirmation, the issue with the 404 error is resolved by merging Ben's PR into develop, and I just merged develop into this branch. So, this one can be reviewed.

**Comment by Civolilah** [comment]
@turbo124 In this PR, #1969  should also be fixed. I cannot recreate the issue that the client reported, so you can also test date pickers and fallback values when an invalid value or action is entered.

**Review by beganovich — APPROVED** [review]

**Pull request merged**
