### PR TITLE
[Bugfix] App Version Checks

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes fixes for checking the version from the correct source. The `api_version` property from the` /api/v1/health_check` endpoint's response is used as the `CURRENT_VERSION`, but the response from `https://pdf.invoicing.co/api/version` is used as the `LATEST_AVAILABLE_VERSION`. If these two versions are `DIFFERENT`, and if the user is `SELF-HOSTED`, and if the `is_docker` property is `FALSE`, then the `force_update` button will be displayed. Let me know your thoughts.

### CODE REVIEW

**Comment by Civolilah** [comment]
@turbo124 This specific PR related to the issue that the client reported on GitHub is pending because I still cannot access:

`https://pdf.invoicing.co/api/version` endpoint.

If I open it in the browser, everything works well and it displays for me, but if I call this endpoint from the local environment, it cannot be accessed because of a CORS issue.

**Comment by turbo124** [comment]
@beganovich thoughts on why this may be occurring?

**Comment by beganovich** [comment]
@turbo124 seems the response doesn't have Access-Control-Allow-Origin. 

Can you make sure that's configured properly on the PDF app?

**Comment by turbo124** [comment]
@beganovich i do not think this is the issue, here are the response headers:

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: X-React,X-API-PASSWORD-BASE64,X-API-COMPANY-KEY,X-API-SECRET,X-API-TOKEN,X-API-PASSWORD,DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Disposition,Range,X-CSRF-TOKEN,X-XSRF-TOKEN,X-LIVEWIRE,X-Socket-Id
Access-Control-Expose-Headers: X-APP-VERSION,X-MINIMUM-CLIENT-VERSION,Content-Disposition
X-APP-VERSION: 5.10.40
X-MINIMUM-CLIENT-VERSION: 5.0.16
Content-Encoding: gzip
```

I've tested from docker / localhost dev build + prod build, but i cannot replicate the issue being seen. Are you able to replicate?1

**Comment by Civolilah** [comment]
> @beganovich i do not think this is the issue, here are the response headers:
> 
> ```
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
> Access-Control-Allow-Headers: X-React,X-API-PASSWORD-BASE64,X-API-COMPANY-KEY,X-API-SECRET,X-API-TOKEN,X-API-PASSWORD,DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Disposition,Range,X-CSRF-TOKEN,X-XSRF-TOKEN,X-LIVEWIRE,X-Socket-Id
> Access-Control-Expose-Headers: X-APP-VERSION,X-MINIMUM-CLIENT-VERSION,Content-Disposition
> X-APP-VERSION: 5.10.40
> X-MINIMUM-CLIENT-VERSION: 5.0.16
> Content-Encoding: gzip
> ```
> 
> I've tested from docker / localhost dev build + prod build, but i cannot replicate the issue being seen. Are you able to replicate?1

@turbo124 @beganovich It looks like a weird issue to me. When I call it with the `fetch` embedded function from JS, it seems the returned status code is 200, but it still shows a CORS issue for me. Screenshot:

Screenshot 2024-10-20 at 16 53 15

When I call it with axios, then it does not show status code 200.

**Comment by beganovich** [comment]
> @beganovich i do not think this is the issue, here are the response headers:
> 
> ```
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
> Access-Control-Allow-Headers: X-React,X-API-PASSWORD-BASE64,X-API-COMPANY-KEY,X-API-SECRET,X-API-TOKEN,X-API-PASSWORD,DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Disposition,Range,X-CSRF-TOKEN,X-XSRF-TOKEN,X-LIVEWIRE,X-Socket-Id
> Access-Control-Expose-Headers: X-APP-VERSION,X-MINIMUM-CLIENT-VERSION,Content-Disposition
> X-APP-VERSION: 5.10.40
> X-MINIMUM-CLIENT-VERSION: 5.0.16
> Content-Encoding: gzip
> ```
> 
> I've tested from docker / localhost dev build + prod build, but i cannot replicate the issue being seen. Are you able to replicate?1

i don't see those headers returned when trying to fetch pdf.invoicing.co, so i can definitely replicate.

**Review by beganovich — APPROVED** [review]

**Pull request merged**
