### PR TITLE
[Feature] Displaying client gateways

### PR DESCRIPTION
**Pull request by Civolilah**
Here is the screenshot of implemented solution for displaying Geteway tokens for client:

Screenshot 2023-01-07 at 13 58 35

@turbo124 This card will be only displayed if we have at least one gateway token assigned to client.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah 

Looking good, couple of changes please.

image

We should be showing Gateway > Stripe instead of Gateway > visa

also, the link should open a new tab (only for stripe gateway)

And the window should open up to:

https://dashboard.stripe.com/customers/{client_gateway_token.customer_gateway_reference}

**Comment by beganovich** [comment]
@turbo124 is this QA passed?

**Comment by turbo124** [comment]
@beganovich LGTM!

**Review by beganovich — APPROVED** [review]
Looks good, however, I'd improve this a bit.

Here's a screenshot of the improved card for better clarity:
- Not a whole div is clickable (it is on Flutter because it's adapter from touch UI)
- Consistent padding around the individual record
- Changed "Gateway tokens" to "Payment methods" as it sounds easier to understand by users (gateway token sounds technical).

@turbo124 let me know the thoughts before I merge.

image

**Comment by turbo124** [comment]
@beganovich agreed on all points.

**Pull request merged**
