### PR TITLE
[Feature] Implementing Clone Line Item Functionality

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the implementation of the clone_line_item functionality for the currently opened entity, as well as across different entities, just like we have with the clone functionality. Screenshots:

Screenshot 2024-06-05 at 19 44 28

Screenshot 2024-06-05 at 21 23 41

Let me know your thoughts.

### CODE REVIEW

**Comment by Civolilah** [comment]
Issue related to the #1788

**Comment by beganovich** [comment]
What's the status on this? QA pending? Revision?

**Comment by Civolilah** [comment]
> What's the status on this? QA pending? Revision?

@beganovich Actually, David wants to think a little bit more about this. David and I discussed the client's request on Slack, so we are not sure if we want to proceed with the exact client's request.

**Comment by turbo124** [comment]
I think for now, we'll close this one. We'll need to consider UI/UX as a whole first prior to taking on these types of challenges.

**Pull request closed without merging**
