### PR TITLE
[Cleanup] Clone option

### PR DESCRIPTION
**Pull request by Civolilah**
@turbo124 Either we were missing the cloning functionality or it was implemented via the` /clone` route on `Project`, `Task` and `Product` entites. It now works like everyone else on the `/create` route. All others have been tested in a production environment and work perfectly. I have now prepared the code for local testing, but I will need to change some small parts of the code to prepare it for production. Let me know your thoughts about functionality.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah 

Cloning on invoices/quotes/credit etc etc are not working. The line items are not resolving after the client is selected.

**Comment by Civolilah** [comment]
> @Civolilah
> 
> Cloning on invoices/quotes/credit etc etc are not working. The line items are not resolving after the client is selected.

@turbo124 As we discussed on the Slack it was behaviour from the React 18, so it works on the production env.

**Comment by beganovich** [comment]
@Civolilah please merge the latest changes which include #375 and make sure to apply same into your code. Thanks 👍

**Comment by Civolilah** [comment]
> @Civolilah please merge the latest changes which include #375 and make sure to apply same into your code. Thanks 👍

@beganovich Sure, as I can see, this is just a condition added for the `production` environment. In that case, I added this condition to the other clone options I managed in this PR (`Product`, `Project`, and `Task`).

**Review by beganovich — APPROVED** [review]
Thanks, looking good 👍

For future reference, I see you did a lot more than just cloning (ie extracting actions, some small refactors, etc) and I am generally happy about that, however, it makes PR harder to review as I focus on cloning mostly while being driven away by extracting actions into separate hooks, etc, so please for future, instead stick to a subject of PR and any additional refactors can go into another PR, I'd gladly accept it.

**Pull request merged**
