### PR TITLE
Migrate select fields to comboboxes

### PR DESCRIPTION
**Pull request by beganovich**
This migrates every select field app to the combobox.

### CODE REVIEW

**Comment by turbo124** [comment]
I'm not seeing this populate as expected in clients.

also, languages still uses old style, are there other combos that need adjusting to this?

**Comment by beganovich** [comment]
@turbo124 it's still work in progress!

**Comment by beganovich** [comment]
Ping @turbo124 for a first QA pass.

**Comment by beganovich** [comment]
Closing in favor of #1194.

**Pull request closed without merging**
