### PR TITLE
Live preview for customize and preview

### PR DESCRIPTION
**Pull request by beganovich**
This improves the live preview page & merges it with old settings for the invoice design.

### CODE REVIEW

**Comment by turbo124** [comment]
@beganovich is this for review?

**Comment by beganovich** [comment]
Implemented a few missing settings. Should be good for review @turbo124 :+1:

**Comment by turbo124** [comment]
image

discount and tax are missing from the quote product columns options.

also, it would be good to show the label for the custom values across the entities. in the options rather than First Custom...

**Comment by turbo124** [comment]
I see these columns in flutter?

image

**Pull request merged**
