### PR TITLE
[Cleanup] Implementing Modal For Search Field In The Top Navbar

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the implementation of a modal for the search field in the top navbar along with all its functionalities. Screenshots:

Screenshot 2024-12-08 at 18 35 56

Screenshot 2024-12-08 at 18 36 17

`Note`: We're missing the "navigate" translation keyword from the files, so if you agree with the current implementation, please add it there.

Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
image

Looks good, can we please remove the border

Also, there was some unusual behaviour of the search dialog

resize

Please inspect the current implementation, we should only have a spinner adjacent to the search text, the search box should never resize inappropriately.

**Comment by Civolilah** [comment]
> image
> 
> Looks good, can we please remove the border
> 
> Also, there was some unusual behaviour of the search dialog
> 
> resize [ resize ](https://private-user-images.githubusercontent.com/5827962/393653334-051d67e2-a3f8-4733-9812-bf8b5d36bd2f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDEwOTcsIm5iZiI6MTczMzc0MDc5NywicGF0aCI6Ii81ODI3OTYyLzM5MzY1MzMzNC0wNTFkNjdlMi1hM2Y4LTQ3MzMtOTgxMi1iZjhiNWQzNmJkMmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMTAzOTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM0ODUxODcyZjFlNDIxZTRjMzc1ODg2M2FhZmQ5NDExZDY0NzY3MDIwODQxNWYwZmU0ZGFjYTFlMzIyYmE0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xS6Qyvywf0CX1vs-muHHTR0ZD05ofH9ft7-rAGpNHQ0) [ ](https://private-user-images.githubusercontent.com/5827962/393653334-051d67e2-a3f8-4733-9812-bf8b5d36bd2f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDEwOTcsIm5iZiI6MTczMzc0MDc5NywicGF0aCI6Ii81ODI3OTYyLzM5MzY1MzMzNC0wNTFkNjdlMi1hM2Y4LTQ3MzMtOTgxMi1iZjhiNWQzNmJkMmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMTAzOTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM0ODUxODcyZjFlNDIxZTRjMzc1ODg2M2FhZmQ5NDExZDY0NzY3MDIwODQxNWYwZmU0ZGFjYTFlMzIyYmE0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.xS6Qyvywf0CX1vs-muHHTR0ZD05ofH9ft7-rAGpNHQ0)
> 
> Please inspect the current implementation, we should only have a spinner adjacent to the search text, the search box should never resize inappropriately.

@turbo124  The border has been removed, and the UX loader has been adjusted. Let me know your thoughts.

**Comment by turbo124** [comment]
resize_me_no_more

just to confirm, the modal should _never_ change size.

**Comment by Civolilah** [comment]
> resize_me_no_more [ resize_me_no_more ](https://private-user-images.githubusercontent.com/5827962/393999745-ef5f0098-fc6f-4db9-96f3-70340615e4e4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3ODQwNTMsIm5iZiI6MTczMzc4Mzc1MywicGF0aCI6Ii81ODI3OTYyLzM5Mzk5OTc0NS1lZjVmMDA5OC1mYzZmLTRkYjktOTZmMy03MDM0MDYxNWU0ZTQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMjIzNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmZmNjU2MGI0OTNkMjQ4ZmYzMjFkYzE1OWU1ZWQ3YTJjMDNlMmE4OWZhOWJiMTI3Mzk4OWU0ODMyYmI1Y2UyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jynsoRFhlQiQ-j3eQghoVOYVFOhl6tZAUjqtS71iDSo) [ ](https://private-user-images.githubusercontent.com/5827962/393999745-ef5f0098-fc6f-4db9-96f3-70340615e4e4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3ODQwNTMsIm5iZiI6MTczMzc4Mzc1MywicGF0aCI6Ii81ODI3OTYyLzM5Mzk5OTc0NS1lZjVmMDA5OC1mYzZmLTRkYjktOTZmMy03MDM0MDYxNWU0ZTQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMjIzNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmZmNjU2MGI0OTNkMjQ4ZmYzMjFkYzE1OWU1ZWQ3YTJjMDNlMmE4OWZhOWJiMTI3Mzk4OWU0ODMyYmI1Y2UyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jynsoRFhlQiQ-j3eQghoVOYVFOhl6tZAUjqtS71iDSo)
> 
> just to confirm, the modal should _never_ change size.

@turbo124 Ah okay, I missed that case. From now on, the height should always be fixed. Screenshot:

Screenshot 2024-12-09 at 23 37 38

Let me know your thoughts.

**Comment by turbo124** [comment]
When using the cursor to navigate, if i press UP, i expect the UI to move back to the search input field, instead it wraps around and goes to the bottom of the list.

**Comment by Civolilah** [comment]
> When using the cursor to navigate, if i press UP, i expect the UI to move back to the search input field, instead it wraps around and goes to the bottom of the list.

@turbo124 Sure thing, when a user is on the first element in the list and clicks the up arrow, the input field will be focused. If the user clicks the up arrow again from the focused field, the first element in the list will be focused again. Also, if the input field is focused and the user clicks the down arrow, the first element in the list will be focused. Let me know your thoughts.

**Comment by beganovich** [comment]
I've encountered a small issue, maybe it's my setup, but if I scroll quickly it kinda jumps all over the place. Can you guys replicate this? @turbo124 @Civolilah 

https://github.com/user-attachments/assets/726df0b3-3f51-4628-8984-1b7a307d9c97

**Comment by Civolilah** [comment]
> I've encountered a small issue, maybe it's my setup, but if I scroll quickly it kinda jumps all over the place. Can you guys replicate this? @turbo124 @Civolilah
> 
>  2024-12-17.16-46-52.mp4

@beganovich Very nice catch! I was able to recreate it, and I've just pushed the fix. Please let me know how it looks on your end.

**Review by beganovich — APPROVED** [review]

**Pull request merged**
