### PR TITLE
[Bugfix] Implementing the missing tax selector for the Limits/Fees page

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the implementation of missing tax selectors on the gateway edit page within the limits/fees tab. Screenshot:

Screenshot 2024-04-19 at 11 47 20

Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah sorry, the taxes should be linked to the number of line item taxes, not invoice taxes

**Comment by Civolilah** [comment]
> @Civolilah sorry, the taxes should be linked to the number of line item taxes, not invoice taxes

@turbo124 Sure, no probs! So now, the number of tax selectors will rely on the `enabled_item_tax_rates` property value. Let me know your thoughts.

**Comment by turbo124** [comment]
@beganovich for hot patch please

**Review by beganovich — APPROVED** [review]

**Comment by beganovich** [comment]
@turbo124 done 👍

**Pull request merged**
