### PR TITLE
[Cleanup] UX Improving Description | Collapsing Description Fields

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes improvements to the UX of the `description` fields in Product tables. Screenshot:

Screenshot 2023-08-10 at 21 00 31

Let me know your thoughts.

### CODE REVIEW

**Comment by Civolilah** [comment]
@turbo124 The edge case that you mentioned in the video of the task ticket has been resolved now. Please let me know your thoughts.

**Comment by turbo124** [comment]
@Civolilah 

I'm still see the same behaviour.

If the last description field has a large amount of text, and the cursor is inside, clicking on the (+) Add Item only collapses the description field, it does not create a new line item. Double click is required.

**Comment by turbo124** [comment]
Still seeing same behaviour here.

**Review by beganovich — APPROVED** [review]
Thanks!

**Pull request merged**
