### PR TITLE
[Feature] Adding Nordigen Connection Option and Creation Connect Accounts Modal

### PR DESCRIPTION
**Pull request by Civolilah**
Done!

### CODE REVIEW

**Comment by Civolilah** [comment]
@turbo124 The implementation of this functionality is complete. As you mentioned in the video, the implementation is custom, so I did not implement tests before receiving your confirmation that you are satisfied with the solution.

The `Yodlee` connection option will be available `ONLY` on the `HOSTED` platform and if the user has an `ENTERPRISE` plan. 
The `Nordigen` connection option will be available on `BOTH` platforms, but on the `HOSTED` platform only if the user has an `ENTERPRISE` plan.

I prepared also quick demo for you:

https://github.com/invoiceninja/ui/assets/51542191/3eee4760-3647-46e8-93da-f82936f67624

Please let me know if you are satisfied with the solution, so I can also add tests.

**Comment by turbo124** [comment]
related issue here, after deleting bank integrations, the list does not refresh.

**Comment by Civolilah** [comment]
@turbo124 As you mentioned in the ticket, Nordigen's connection URL has now changed depending on the platform that the user is using. Let me know your thoughts.

**Comment by turbo124** [comment]
@beganovich please review, but do not merge until API changes are ready.

**Comment by paulwer** [comment]
@Civolilah @turbo124 Nordigen with their Bank Account Data APIs were aquired by GoCardless. So the Company Nordigen does not exists anymore. Maybe we should respect this while branding in frontend?

**Comment by turbo124** [comment]
> @Civolilah @turbo124 Nordigen with their Bank Account Data APIs were aquired by GoCardless. So the Company Nordigen does not exists anymore. Maybe we should respect this while branding in frontend?

Sure, sounds fair enough

**Comment by paulwer** [comment]
@Civolilah @turbo124 does this PR also cover reconnect of expired accounts or is it just the modal?

**Comment by Civolilah** [comment]
> @Civolilah @turbo124 does this PR also cover reconnect of expired accounts/requisitions or is it just the modal?

**Comment by Civolilah** [comment]
> @Civolilah @turbo124 does this PR also cover reconnect of expired accounts/requisitions or is it just the modal?

@paulwer The PR currently includes this modal along with the Nordigen connection. I believe @turbo124 can provide more information about the near-future plans.

**Comment by Civolilah** [comment]
@beganovich @turbo124 Today, I implemented a test for the `Nordigen` connection as well. So, once the API is ready, the PR is prepared for merging.

**Comment by Civolilah** [comment]
@beganovich @turbo124 Moving to draft just to find an appropriate logo for `Nordigen`.

**Comment by turbo124** [comment]
@Civolilah 

use this for resources:

https://www.dropbox.com/s/ae29qs3mmfuiymu/gocardless-logo-pack.zip?dl=0

**Comment by Civolilah** [comment]
> @Civolilah
> 
> use this for resources:
> 
> https://www.dropbox.com/s/ae29qs3mmfuiymu/gocardless-logo-pack.zip?dl=0

@turbo124 As we discussed on Slack, the flow has been slightly changed. So, if the user is self-hosted, once they click the 'connect_accounts' button, they will be immediately navigated to the tab for Nordigen connection. However, if it is a HOSTED platform, then the modal will be opened. Also, the logo has been changed; it looks like this:

Screenshot 2023-12-26 at 02 14 35

Let me know your thoughts.

**Comment by turbo124** [comment]
looks good, thanks!

**Review by beganovich — APPROVED** [review]

**Comment by turbo124** [comment]
@beganovich ready for merge please.

**Review by beganovich — APPROVED** [review]

**Pull request merged**
