### PR TITLE
[Feature] Expense table - client overview page

### PR DESCRIPTION
**Pull request by Civolilah**
Here is the screenshot of implemented expense table on the client overview page:

Screenshot 2023-01-15 at 15 05 51

### CODE REVIEW

**Review by beganovich — APPROVED** [review]
Looks good, thanks 👍

**Comment by beganovich** [comment]
Ping @Civolilah for conflicts.

**Comment by Civolilah** [comment]
> Ping @Civolilah for conflicts.

@beganovich Resolved conflicts!

**Comment by beganovich** [comment]
Thanks 👍

**Pull request merged**
