### PR TITLE
[Cleanup] Company Wizard

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the refactoring of the company edit modal for `HOSTED` users. It has been transformed into a company wizard with three steps. To ensure thorough testing, I have created a quick video as a tour through the wizard. Video:

https://github.com/invoiceninja/ui/assets/51542191/5e267cb0-ae74-41f8-bb68-06b9be5c22e6

However, for `SELF-HOSTED` users, we keep the wizard the same, with just one step.

`One note`: David, if you agree with the entire setup, I've added the `connect_stripe` translation keyword for the text on the button for connecting Stripe in the third step. Please just add it to the translation files.

Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
Please change translation of skip to next. thanks.

**Comment by Civolilah** [comment]
> Please change translation of skip to next. thanks.

@turbo124 Sure, changed!

Screenshot 2023-12-06 at 14 49 47

**Review by beganovich — COMMENTED** [review]
Seems odd to technically rebuilt tabs system with this. If possible it'd be good to re-use tabs since you can dynamically change visible tab, too.

Let me know if it's not possible.

**Comment by Civolilah** [comment]
> Seems odd to technically rebuilt tabs system with this. If possible it'd be good to re-use tabs since you can dynamically change visible tab, too.
> 
> Let me know if it's not possible.

@beganovich I understand your point, but I have already implemented the solution with the `Back` button, and David suggested that I remove it and leave it as is. So, I'm not sure if we want tabs instead of this UI. @turbo124, could you please provide some advice?

**Comment by turbo124** [comment]
@beganovich not sure the juice is worth the squeeze for a refactor as I do not think this particular component will be extended further.

**Comment by beganovich** [comment]
Sure thing guys, np.

@Civolilah ping for merge conflict.

**Pull request merged**
