### PR TITLE
[Cleanup] Import Template Keys

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes changing the approach to checking duplicates of import templates. If I correctly understand this ticket (https://invoiceninja.atlassian.net/browse/RU-1614), I think the confusion comes from the issue you mentioned in the last part of the ticket's description. I used all template names in lower case, so "test" was considered a duplication of "TEST". I've changed the approach now so that the entered text is the key of the template. Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
image


I am seeing a range of integers rather than the template names.

**Comment by Civolilah** [comment]
> image
> 
> I am seeing a range of integers rather than the template names.

@turbo124 Hmm, that is weird. I just tested production on my own account on the blank company and also did a new seed of the data locally so I can test it from scratch. I also checked the logic and flow in the code, and it looks like I never deal with indexes when displaying values in the dropdown. This is the screenshot from the production:

Screenshot 2024-09-20 at 18 31 59

Are you sure that the template names are not entered like that? Because it looks to me like impossible case when looking in the logic.

**Comment by turbo124** [comment]
```
{
    "table_filters": {
        "\/dashboard\/api\/v1\/invoices?include=clientgroup_settings&overdue=true&without_deleted_clients=true&per_page=50&page=1&sort=due_date|asc": {
            "sort": "id|asc",
            "status": [
                "active"
            ]
        }
    },
    "import_templates": {
        "bank_transaction": [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            [
                null,
                null,
                "transaction.amount",
                null,
                null,
                null,
                "transaction.date",
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                "transaction.payment_type_Credit",
                "transaction.category",
                null,
                null
            ]
        ]
    },
    "common_actions": {
        "invoice": [
            "view_pdf"
        ]
    }
}
```

this is a sample of the react_settings, i'm not sure if it sheds any light on this. Are we constraining the templates to the entities? ie, only invoice import templates are shown on the invoice import page?

**Comment by Civolilah** [comment]
> ```
> {
>     "table_filters": {
>         "\/dashboard\/api\/v1\/invoices?include=clientgroup_settings&overdue=true&without_deleted_clients=true&per_page=50&page=1&sort=due_date|asc": {
>             "sort": "id|asc",
>             "status": [
>                 "active"
>             ]
>         }
>     },
>     "import_templates": {
>         "bank_transaction": [
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             null,
>             [
>                 null,
>                 null,
>                 "transaction.amount",
>                 null,
>                 null,
>                 null,
>                 "transaction.date",
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 null,
>                 "transaction.payment_type_Credit",
>                 "transaction.category",
>                 null,
>                 null
>             ]
>         ]
>     },
>     "common_actions": {
>         "invoice": [
>             "view_pdf"
>         ]
>     }
> }
> ```
> 
> this is a sample of the react_settings, i'm not sure if it sheds any light on this. Are we constraining the templates to the entities? ie, only invoice import templates are shown on the invoice import page?

@turbo124 This is crazy, how this issue even happened. But I've created logic that will avoid this issue, and every future template save will have only correct details. Please let me know if these adjustments have fixed it for you.

**Review by beganovich — APPROVED** [review]

**Pull request merged**
