### PR TITLE
[Feature] Quote Slider

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the implementation of the Quote Slider. Screenshot:

Screenshot 2024-02-12 at 19 28 27

Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah look good,  can we please bundle into this PR refactor of clone options to align with invoice more actions please to  reduce the number of clone options in the list

image

**Comment by Civolilah** [comment]
> @Civolilah look good, can we please bundle into this PR refactor of clone options to align with invoice more actions please to reduce the number of clone options in the list
> 
> image

@turbo124 Hmm, it looks to me like the exact same approach we have on the Invoice Slider. We have the option "Clone to Quote" and the second one "Clone to Other." The "Clone to Other" action will open the modal with the rest of the clone options, all other actions are not related to clone option actions.

Screenshot 2024-02-13 at 16 09 52

Did I miss something?

**Comment by turbo124** [comment]
@Civolilah my mistake, the convert to invoice action confused me.

**Comment by beganovich** [comment]
> > @Civolilah look good, can we please bundle into this PR refactor of clone options to align with invoice more actions please to reduce the number of clone options in the list
> > image
> 
> @turbo124 Hmm, it looks to me like the exact same approach we have on the Invoice Slider. We have the option "Clone to Quote" and the second one "Clone to Other." The "Clone to Other" action will open the modal with the rest of the clone options, all other actions are not related to clone option actions.
> Screenshot 2024-02-13 at 16 09 52
> 
> Did I miss something?

I think this UI looks awful. There's no clear distinction where the button starts or ends. Please make it full width and perhaps use visual vertical separator (divide-y).

**Comment by Civolilah** [comment]
> > > @Civolilah look good, can we please bundle into this PR refactor of clone options to align with invoice more actions please to reduce the number of clone options in the list
> > > image
> > 
> > 
> > @turbo124 Hmm, it looks to me like the exact same approach we have on the Invoice Slider. We have the option "Clone to Quote" and the second one "Clone to Other." The "Clone to Other" action will open the modal with the rest of the clone options, all other actions are not related to clone option actions.
> > Screenshot 2024-02-13 at 16 09 52
> > Did I miss something?
> 
> I think this UI looks awful. There's no clear distinction where the button starts or ends. Please make it full width and perhaps use visual vertical separator (divide-y).

@beganovich @turbo124 Certainly, the secondary button seems like a great option to me for improving the UI/UX here. Screenshot:

Screenshot 2024-02-15 at 10 03 45

Let me know your thoughts.

**Comment by turbo124** [comment]
I'll leave the final decision to @beganovich

**Review by beganovich — APPROVED** [review]

**Pull request merged**
