### PR TITLE
[Bugfix] 2FA Workflow When User Save User Details Changes

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes fixing the logic and workflow for displaying modals when a user saves changes to their user details for 2FA. Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
@beganovich could you merge to beta please for uat.

**Review by beganovich — APPROVED** [review]

**Comment by beganovich** [comment]
@turbo124 beta is now deployed with `VITE_FEATURE_2FA` in the build.

**Comment by turbo124** [comment]
@beganovich 

thanks, functionality confirmed working.

**Comment by beganovich** [comment]
I guess it's fine to remove the feature flag now, @turbo124 ?

**Pull request merged**
