### PR TITLE
Move custom fields to the settings

### PR DESCRIPTION
**Pull request by beganovich**
This moves custom fields back to the settings.

### CODE REVIEW

**Comment by turbo124** [comment]
Can we move these into tabs please

**Comment by beganovich** [comment]
Ping @turbo124 for QA pass.

**Comment by turbo124** [comment]
Please hide tabs for Quotes / Credits these do not exist, we reuse the Invoice ones for these. otherwise looks good.

**Comment by beganovich** [comment]
Ping @turbo124 for another QA pass.

**Pull request merged**
