### PR TITLE
Unify templates & designs interface

### PR DESCRIPTION
**Pull request by beganovich**
This supersedes #1143.

### CODE REVIEW

**Comment by turbo124** [comment]
this looks good.

Could you please update the list of entities to accept the following:

```
private array $valid_entities = [
        'invoice',
        'payment',
        'client',
        'quote',
        'credit',
        'purchase_order',
        'project',
        'task'
    ];
```

**Comment by turbo124** [comment]
Looks good.

Minor fixes:

Please change translations:

change_template to `load_template`
generate_template to `run_template`

Then good to merge

**Comment by turbo124** [comment]
Just following this one, are we also merging #1143 ? because i cannot see default designs in #1300

**Comment by turbo124** [comment]
One issue i've notice, when previewing the templates, i am not seeing the entities field being updated/persisted

**Comment by beganovich** [comment]
Ping @turbo124 for QA pass.

**Comment by turbo124** [comment]
@beganovich just a heads up I've updated some elements of this PR.

**Comment by beganovich** [comment]
Ping @turbo124 for QA pass 👍️

**Pull request closed without merging**
