### PR TITLE
[Cleanup] Product Selector Label | Track Inventory

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes improving product labels on the invoice creation and edit pages, including stock quantity. So, if `track_inventory` is turned on, and we have `stock_quantity` greater than 0, we will show the actual number. If it is zero or a negative number, we will show the "Out of Stock" text. Screenshot:

Screenshot 2023-09-23 at 17 52 18

@turbo124 We do not have the translation keywords `in_stock` and `out_of_stock` in the files. If you agree with me, please add them there.

Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah 

I've added a translation:

key

```
stock_quantity
```

value

```
Stock :quantity
```

For this translation, just pass the stock quantity variable into the translation. also, if quantity > 0 keep text color black, if stock quantity <= 0 text color red please.

**Comment by Civolilah** [comment]
> @Civolilah
> 
> I've added a translation:
> 
> key
> 
> ```
> stock_quantity
> ```
> 
> value
> 
> ```
> Stock :quantity
> ```
> 
> For this translation, just pass the stock quantity variable into the translation. also, if quantity > 0 keep text color black, if stock quantity <= 0 text color red please.

@turbo124 All your suggestions are implemented, let me know your thoughts.

**Comment by turbo124** [comment]
image

not sure why the label here has been replaced,

The intent was for the translation to be used in place of this one here:

image

**Comment by Civolilah** [comment]
> @Civolilah
> 
> Can you please replace this label translation with this key please:
> 
> ```
> stock_quantity_number
> ```
> 
> The translation key stock_quantity already exists.

@turbo124 Sure, changed!

**Pull request merged**
