### PR TITLE
[Cleanup] Prevent Page Leaving Reimplementation

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the reimplementation of the "prevent page leaving" functionality from the Slack discussion. Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah were you able to find the issue here? just ping when we should attempt another review.

**Comment by Civolilah** [comment]
> @Civolilah were you able to find the issue here? just ping when we should attempt another review.

@turbo124 I found the edge case issue and then refactored the solution to fix it. Please let me know if you are seeing the correct behavior in all cases now.

**Comment by turbo124** [comment]
@Civolilah I think we are close.

One set of edge cases to resolve.

Need to be careful with the implementation of this when a user uses a More Actions command.

For example, if the user clicks Mark Sent. Then the change modal should not be displayed.
Alternatively, when clicking on Enter Payment, you would need to present the modal for any changes that are yet to be saved.

**Comment by Civolilah** [comment]
@turbo124 I just merged the develop branch into this one to remove the tiny, unnecessary logic for the `back` button that we no longer have. I finished it, and the PR is ready for final review. Let me know your thoughts.

**Comment by turbo124** [comment]
@beganovich this looks good from my testing. We'll need a way to disable this if unexpected edge case appear.

**Comment by Civolilah** [comment]
> @beganovich this looks good from my testing. We'll need a way to disable this if unexpected edge case appear.

@turbo124 @beganovich I just implemented the disabling of this functionality if something goes wrong. It will be controlled through the .env variable `VITE_DISABLE_PREVENT_NAVIGATION_FEATURE`. If this is set to `true`, the functionality will not be available.

**Review by beganovich — APPROVED** [review]

**Comment by beganovich** [comment]
@turbo124 feel free to merge after confirmation that this feature is _disabled_ by default (VITE_DISABLE_PREVENT_NAVIGATION_FEATURE=true).

**Review by beganovich — APPROVED** [review]

**Pull request merged**
