### PR TITLE
[Feature] Implementing "view_task" and "view_expense" Actions For Line Items

### LINKED ISSUE #1811: Ability to navigate back to related task in invoice line items
In the Flutter app, it's possible to navigate to the linked task for a given Task line item in an invoice. This is currently not possible in the React UI.

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the implementation of "view_task" and "view_expense" for invoices at the line item level. Once the user clicks on the action, a new tab will open to the edit page of the entity (task/expense). Screenshot:

Screenshot 2024-06-11 at 18 21 58

Screenshot 2024-06-11 at 17 53 37

Closes #1811 

Let me know your thoughts.

### CODE REVIEW

**Comment by Civolilah** [comment]
@turbo124 Currently, this is implemented for the line items on the edit invoice page. I think there are no other cases for line items where these actions need to be displayed?

**Comment by turbo124** [comment]
@Civolilah just invoices.

**Comment by Civolilah** [comment]
> @Civolilah just invoices.

@turbo124 Okay, then I can confirm that it is implemented for invoices and you can review it.

**Comment by turbo124** [comment]
Lets chat on slack on this one.

**Pull request closed without merging**
