### PR TITLE
[Feature] Reactivate Email Action For Events In Email History

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes implementing a new CTA for events in Email History. So, when the event has the `bounce_id` property populated, we will display a `reactivate` CTA and call the endpoint when the user clicks on the button. Screenshot:

Screenshot 2023-10-23 at 10 40 23

Let me know your thoughts.

### CODE REVIEW

**Comment by Civolilah** [comment]
@turbo124 Is the API not yet prepared for this action?

**Comment by turbo124** [comment]
@Civolilah API not ready yet. we can review and have it pending API

**Comment by Civolilah** [comment]
> @Civolilah API not ready yet. we can review and have it pending API

@turbo124 Sure, everything should be prepared in the PR to work properly. Once we have the API ready, you can review it immediately. Thanks!

**Comment by turbo124** [comment]
@beganovich can be reviewed, but not merged yet please.

**Review by beganovich — APPROVED** [review]
LGTM, let me know when it's good to merge @turbo124.

**Review by beganovich — APPROVED** [review]

**Pull request merged**
