### PR TITLE
Help widget

### PR DESCRIPTION
**Pull request by beganovich**
This adds a tiny help widget on the right side of the screen with some preprocessing. It's kept on screen even when clicking outside so you don't have to fight with it. It will stay open, you can scroll, follow the guide and use the app in the "background".

- Relative assets URLs are swapped
- `<x-next>` is gone
- Any layout metadata is gone

We can directly point the URL to the documentation as a source.

```tsx
<HelpWidget
  id="import-and-export"
  url="https://raw.githubusercontent.com/invoiceninja/invoiceninja.github..."
/>
```

image

### CODE REVIEW

**Comment by turbo124** [comment]
@beganovich looks good :+1:

**Comment by beganovich** [comment]
now it includes support for dark mode & side switching in case content gets in the way.

**Comment by beganovich** [comment]
@turbo124 can you update `public/example-imports/invoices.csv` please?

**Comment by turbo124** [comment]
Can we add a link at the bottom to also navigate the user (in a new window) to the help docs please.

**Comment by turbo124** [comment]
> @turbo124 can you update `public/example-imports/invoices.csv`, please?

the full doc url is:

https://invoiceninja.github.io/assets/example-imports/invoices.csv

is that ok?

**Comment by beganovich** [comment]
looks good, thanks :+1:

**Pull request merged**
