### PR TITLE
[Cleanup] Client & Vendor Overview Pages More Actions For Tables

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the removal of edit buttons from the navigation bar for Vendor and Client overview pages. We did the same thing for the `Project` overview page and placed it in the `more_actions` dropdown. Here is a screenshot of the Client overview page:

Screenshot 2023-07-02 at 17 52 44

Otherwise, I cannot see any other differences between the main table pages for entities and the overview/edit pages for the same entities regarding the `more_actions` dropdown, as we use the same hook to display them.

Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
was this part of a jira task? the current UX is correct.

**Comment by Civolilah** [comment]
> was this part of a jira task? the current UX is correct.

@turbo124 This PR is created regarding this Jira task: https://invoiceninja.atlassian.net/browse/RU-877. Here if I correctly understand, the issue is reported that we do not have the same actions in the `more_actions` dropdown on the `Overview` page as on the main table page for the `Client` entity. I checked the code, and everywhere we use the same hook for actions across the app, so there should not be any differences.

We performed the same refactoring on the Project overview page by moving the `edit_project` button to the `more_actions` dropdown. So, I thought that was the only difference we had and wanted to address.

Since you mentioned that the current UX for those pages is correct, I'm not sure if I can see any differences in the `more_actions` dropdowns on the main table pages and overview pages, especially for Client pages, in the code or on the UI.

Screenshots:

Screenshot 2023-07-03 at 01 03 32

Screenshot 2023-07-03 at 01 03 51

If there are any differences, please let me know, and I will refactor this PR to fix them.

**Comment by Civolilah** [comment]
@turbo124 As we discussed on Slack, this PR is now related to matching the `more_actions` dropdowns for tables on the overview pages for `Clients`, `Vendors`, and `Projects`. Screenshot:

Screenshot 2023-07-03 at 20 40 15

You will probably be able to recreate the bug of not having archive/delete/restore actions on the Recurring Expense edit page, but that is a separated task that will be completed very soon as well.

Let me know your thoughts.

**Comment by turbo124** [comment]
Looks good!

**Review by beganovich — APPROVED** [review]
Looks good, thanks :+1:

**Pull request merged**
