### PR TITLE
[Feature] Client Portal Instruction Tooltip

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 For now, PR only includes this `Instruction Tooltip` as a helper on the `Client Portal` page for displaying idea. Screenshot:

Screenshot 2023-04-18 at 06 16 44

`Important note`: On the ticket (https://invoiceninja.atlassian.net/browse/RU-397) Shalom did not specified helper texts or anything like that. So David, if you can, please just give me more instructions where I should use the `Tooltip helper,` but where just `plain helper text` like we have in many other fields.

Let me know your thoughts about my idea for Tooltip instruction helper.

### CODE REVIEW

**Comment by Civolilah** [comment]
> 

@turbo124 Sure, it is done, so this helper text will be only displayed for `HOSTED` users and when `company.portal_mode === 'domain'`. Screenshot:

Screenshot 2023-04-19 at 06 03 15

Empty space between words will be made by the result of `app_help_link` keyword, 'More information '.

Let me know your thoughts.

**Comment by turbo124** [comment]
@Civolilah 

just to confirm, will the text display under Domain ? and not Login ?

**Comment by Civolilah** [comment]
> 

a

**Comment by Civolilah** [comment]
> @Civolilah
> 
> just to confirm, will the text display under Domain ? and not Login ?

@turbo124 This will be display just under `Login URL` text as on the screenshot above. Should I change it to be displayed under domain?

**Comment by turbo124** [comment]
Yes it sounds appear under the domain text that has the portal_domain input field

**Comment by Civolilah** [comment]
> Yes it sounds appear under the domain text that has the portal_domain input field

@turbo124 Sure, it is changed. And, this is how it will look like on the hosted platform:

Screenshot 2023-04-20 at 07 01 37

Let me know your thoughts.

**Review by beganovich — APPROVED** [review]

**Pull request merged**
