### PR TITLE
[Feature] Import Templates

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes the implementation for the templates in imports. Screenshots:

Screenshot 2024-02-27 at 15 42 06

Screenshot 2024-02-25 at 06 58 56

Note: If you agree with the translation keyword "save_sa_template" as the title on the modal, please just add it to the files.

Let me know your thoughts.

### CODE REVIEW

**Comment by Civolilah** [comment]
@turbo124 As we discussed, the flow of this feature has been slightly changed. Now, after successfully importing the file, we will offer to save the selected column_map as a template, if desired. Regarding the change in flow, I also made slight adjustments to the modal for saving the template. Let me know your thoughts.

**Comment by Civolilah** [comment]
@turbo124 As we discussed today, there is one more modal added here for improving UX, before opening the final modal for saving the actual template. Once we get the translated keyword, it will be replaced with the text from the screenshot. Screenshot:

Screenshot 2024-02-28 at 16 48 19

Let me know your thoughts.

**Comment by turbo124** [comment]
Please provide a Yes and No button options please.

**Comment by Civolilah** [comment]
> Please provide a Yes and No button options please.

@turbo124 Sure, the "No" button is now also implemented. Screenshot:

Screenshot 2024-02-29 at 13 50 23

Let me know your thoughts.

**Comment by turbo124** [comment]
@Civolilah 

this looks good, after the user  has acknowledged the modal, can you please redirect automatically to the listview of the entity please.

**Comment by Civolilah** [comment]
> @Civolilah
> 
> this looks good, after the user has acknowledged the modal, can you please redirect automatically to the listview of the entity please.
> 
> also, we should standardize the delete / trash icons we are using, can you ensure this is consistent across the app
> 
> image

@turbo124 Sure, so redirection is adjusted just as we discussed. Also, the trash icon is always the same from the same package across the whole app. I just chose the red color instead of our convention to use the accent color. So, I changed just that detail. Screenshot:

Screenshot 2024-03-01 at 00 31 24

Let me know your thoughts.

**Review by beganovich — APPROVED** [review]

**Pull request merged**
