### PR TITLE
[Feature] Sidebar Background Color

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 PR includes adding a field to customize the background color on the left main sidebar. Screenshot:

Screenshot 2023-04-23 at 02 50 33

`Important note`: Updating this property in the DB does not work. David, please just do a quick check and let me know if you need anything from me. I used `sidebar_background` as the property name under the `react_settings` object.

`Suggestion`: Some parts of the feature are dynamically calculated, but what I couldn't dynamically calculate was the text and icon color. Users will not be able to select some colors because the contrast may be poor, and the text and icons may be almost or completely invisible. My suggestion is to also add a custom color for this purpose, that color will be applied to the text and icons.

Let me know your thoughts.

### CODE REVIEW

**Comment by turbo124** [comment]
@Civolilah 

This looks good, we may pause this PR until we complete the dark mode integration.

**Comment by Civolilah** [comment]
> 

@turbo124 Okay, in that case I will move this PR in the draft. Should I create ticket for implementing dark mode?

**Comment by turbo124** [comment]
@Civolilah we have this ticket already allocated.

**Comment by Civolilah** [comment]
> @Civolilah we have this ticket already allocated.

@turbo124 Ah sorry, I forgot it, thanks for letting me know.

**Comment by turbo124** [comment]
closing in favour of user preferences

**Pull request closed without merging**
